services:

    _defaults:
        autoconfigure: true
        autowire:      true

    Jmf\RenderingPreset\:
        resource: '../src/'

    Jmf\RenderingPreset\Preset\PresetRepository:
        factory: ['@Jmf\RenderingPreset\Preset\PresetRepositoryFactory', 'create']
        arguments:
            - '%jmf_rendering_preset.preset_configurations%'
            - '%jmf_rendering_preset.property_configurations%'

    Jmf\RenderingPreset\Preset\PresetRepositoryInterface:
        alias: Jmf\RenderingPreset\Preset\PresetRepository

    Jmf\RenderingPreset\Twig\RenderingPresetExtension:
        arguments:
            $prefix: '%jmf_rendering_preset.twig_functions_prefix%'

    Jmf\TemplateRendering\TemplateRendererInterface:
        class: Jmf\TemplateRendering\TemplateRenderer
